# Generated by Django 5.2.3 on 2025-07-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True, null=True),
        ),
    ]
