# Generated by Django 5.2.3 on 2025-07-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='template_code',
            field=models.TextField(blank=True),
        ),
    ]
