# Generated by Django 5.2.3 on 2025-07-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_problem_slug_problem_solution_problem_template_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='solution',
        ),
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True, help_text='Problem constraints'),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_format',
            field=models.TextField(blank=True, help_text='Format of input data'),
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.PositiveIntegerField(default=128, help_text='Memory limit in MB'),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_format',
            field=models.TextField(blank=True, help_text='Format of expected output'),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_input',
            field=models.TextField(blank=True, help_text='Sample input data'),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_output',
            field=models.TextField(blank=True, help_text='Sample output data'),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.PositiveIntegerField(default=2, help_text='Time limit in seconds'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='template_code',
            field=models.TextField(blank=True, help_text='Initial code template'),
        ),
    ]
