# Generated by Django 5.2.3 on 2025-07-05 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_remove_problem_solution_problem_constraints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='template_code',
        ),
    ]
