# Generated by Django 5.2.3 on 2025-07-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_remove_problem_template_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='template_code',
            field=models.TextField(blank=True, help_text='Initial code template'),
        ),
    ]
